services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: holly
    restart: unless-stopped
    networks:
      default:
      proxy:
    environment:
      CORS_ALLOW_ORIGIN: https://holly
      OLLAMA_BASE_URL: http://ollama:11434
    labels:
      traefik.enable: true
      traefik.http.routers.holly.rule: Host(`holly`)
      traefik.http.routers.holly.middlewares: trusted-ipallowlist
    volumes:
      - /containers/holly:/app/backend/data
      - /var/cache/holly:/app/backend/data/cache

networks:
  default:
    enable_ipv6: true
  proxy:
    external: true
