services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    restart: unless-stopped
    networks:
      default:
      proxy:
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    labels:
      traefik.enable: true
      traefik.http.routers.ollama.rule: Host(`ollama`)
      traefik.http.routers.ollama.middlewares: trusted-ipallowlist
    volumes:
      - /containers/ollama-open-webui:/app/backend/data
      - /var/tmp/ollama-open-webui:/app/backend/data/cache

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - /containers/ollama-ollama:/root/.ollama

networks:
  proxy:
    external: true
