services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: eve
    restart: unless-stopped
    networks:
      default:
      ollama:
      proxy:
    environment:
      CORS_ALLOW_ORIGIN: https://eve
      OLLAMA_BASE_URL: http://ollama:11434
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID:?OAUTH_CLIENT_ID is required}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET:?OAUTH_CLIENT_SECRET is required}
      OPENID_PROVIDER_URL: https://auth.home.joe.nyland.io/application/o/eve/.well-known/openid-configuration
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      ENABLE_LOGIN_FORM: false
      ENABLE_OAUTH_SIGNUP: true
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    labels:
      traefik.enable: true
      traefik.http.routers.eve.rule: Host(`eve`)
      traefik.http.routers.eve.middlewares: trusted-ipallowlist
    volumes:
      - /containers/eve-open-webui:/app/backend/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

networks:
  default:
    enable_ipv6: true
  ollama:
    external: true
  proxy:
    external: true
